import os
import uuid
import sqlite3
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Rate limiting
# ---------------------------------------------------------------------------
limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ---------------------------------------------------------------------------
# Database / audit log
# ---------------------------------------------------------------------------
DB_PATH = "provenance.db"


def init_db():
    con = sqlite3.connect(DB_PATH)
    con.execute("""
        CREATE TABLE IF NOT EXISTS audit_log (
            content_id  TEXT PRIMARY KEY,
            creator_id  TEXT NOT NULL,
            timestamp   TEXT NOT NULL,
            attribution TEXT NOT NULL,
            confidence  REAL NOT NULL,
            llm_score   REAL NOT NULL,
            stylo_score REAL,
            label_text  TEXT NOT NULL,
            status      TEXT NOT NULL DEFAULT 'classified',
            appeal_id   TEXT,
            appeal_reason TEXT,
            appealed_at TEXT
        )
    """)
    con.commit()
    con.close()


def log_decision(entry: dict):
    con = sqlite3.connect(DB_PATH)
    con.execute("""
        INSERT INTO audit_log
            (content_id, creator_id, timestamp, attribution, confidence,
             llm_score, stylo_score, label_text, status)
        VALUES
            (:content_id, :creator_id, :timestamp, :attribution, :confidence,
             :llm_score, :stylo_score, :label_text, :status)
    """, entry)
    con.commit()
    con.close()


def get_log(limit: int = 20) -> list:
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        "SELECT * FROM audit_log ORDER BY timestamp DESC LIMIT ?", (limit,)
    ).fetchall()
    con.close()
    return [dict(r) for r in rows]


def get_entry(content_id: str) -> dict | None:
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    row = con.execute(
        "SELECT * FROM audit_log WHERE content_id = ?", (content_id,)
    ).fetchone()
    con.close()
    return dict(row) if row else None


# ---------------------------------------------------------------------------
# Detection Signal 1: LLM classifier (Groq)
# ---------------------------------------------------------------------------
groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LLM_PROMPT = """You are an AI-content detection assistant. Analyze the text below and
assess whether it was written by a human or generated by an AI.

Return ONLY valid JSON in exactly this format (no markdown, no explanation):
{{
  "ai_probability": <float between 0.0 and 1.0>,
  "reasoning": "<one sentence>"
}}

Where ai_probability is 0.0 for definitely human and 1.0 for definitely AI-generated.

Text to analyze:
\"\"\"
{text}
\"\"\""""


def classify_with_llm(text: str) -> float:
    """Return ai_probability (0–1) from Groq LLM classifier."""
    # Truncate to ~1500 tokens to stay within limits
    truncated = text[:6000]
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": LLM_PROMPT.format(text=truncated)}],
            temperature=0.0,
            max_tokens=100,
        )
        import json
        raw = response.choices[0].message.content.strip()
        data = json.loads(raw)
        score = float(data["ai_probability"])
        return max(0.0, min(1.0, score))  # clamp to [0, 1]
    except Exception as e:
        app.logger.error(f"LLM classification failed: {e}")
        return 0.5  # neutral fallback on error


# ---------------------------------------------------------------------------
# Detection Signal 2: Stylometric Heuristics
# ---------------------------------------------------------------------------
import re
import math

def compute_stylometric_score(text: str) -> float:
    """
    Compute a 0-1 score toward AI based on three stylometric sub-metrics:
      1. Sentence-length variance (low variance = AI-like)
      2. Type-token ratio (low diversity = AI-like)
      3. Punctuation density (near-average = AI-like)
    Returns 0.5 as fallback for very short texts (< 3 sentences).
    """
    # Split into sentences
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) < 3:
        return 0.5  # not enough data

    # 1. Sentence-length variance (normalized)
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    # AI text: std_dev typically < 5; human text > 8
    # Normalize: low std_dev → high score
    sent_score = max(0.0, min(1.0, 1.0 - (std_dev / 15.0)))

    # 2. Type-token ratio (vocabulary diversity)
    words = re.findall(r'\b\w+\b', text.lower())
    if len(words) == 0:
        ttr_score = 0.5
    else:
        ttr = len(set(words)) / len(words)
        # AI text: ttr ~0.5-0.6; human text: more variable, often higher
        # Low TTR → high score (AI-like)
        ttr_score = max(0.0, min(1.0, 1.0 - ttr))

    # 3. Punctuation density
    punct_count = sum(1 for c in text if c in '.,;:!?-()"\' ')
    total_chars = len(text)
    if total_chars == 0:
        punct_score = 0.5
    else:
        punct_density = punct_count / total_chars
        # AI text has moderate, consistent punctuation (~0.15-0.25)
        # Score high if density is in that "average" range
        distance_from_avg = abs(punct_density - 0.20)
        punct_score = max(0.0, min(1.0, 1.0 - (distance_from_avg / 0.20)))

    # Average the three sub-metrics
    stylo_score = (sent_score + ttr_score + punct_score) / 3.0
    return round(stylo_score, 4)


# ---------------------------------------------------------------------------
# Label generation
# ---------------------------------------------------------------------------
def generate_label(confidence: float) -> tuple[str, str]:
    """Return (attribution, label_text) based on confidence score."""
    if confidence <= 0.35:
        return (
            "human",
            "This content appears to be human-written. Our system found no strong "
            "indicators of AI generation.",
        )
    elif confidence < 0.75:
        return (
            "uncertain",
            "Our system is uncertain about the origin of this content. It may be "
            "human-written, AI-generated, or a mix. If you are the creator and believe "
            "this label is wrong, you can submit an appeal.",
        )
    else:
        return (
            "ai_generated",
            "Our system detected strong indicators that this content was AI-generated. "
            "If you are the creator and believe this is incorrect, you can submit an appeal.",
        )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;50 per day")
def submit():
    body = request.get_json(silent=True)
    if not body or "text" not in body or "creator_id" not in body:
        return jsonify({"error": "Missing required fields: text, creator_id"}), 400

    text = body["text"].strip()
    creator_id = body["creator_id"].strip()

    if not text:
        return jsonify({"error": "text must not be empty"}), 400

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    # Signal 1: LLM classifier
    llm_score = classify_with_llm(text)

    # Signal 2: Stylometric heuristics
    stylo_score = compute_stylometric_score(text)

    # Confidence: weighted average per planning.md (0.6 LLM + 0.4 stylo)
    confidence = round(0.6 * llm_score + 0.4 * stylo_score, 4)
    attribution, label_text = generate_label(confidence)

    short_text_warning = len(text.split()) < 80

    # Write to audit log
    log_decision({
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "label_text": label_text,
        "status": "classified",
    })

    response = {
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label_text": label_text,
        "signals": {
            "llm_score": round(llm_score, 4),
            "stylo_score": round(stylo_score, 4),
        },
    }
    if short_text_warning:
        response["short_text_warning"] = True

    return jsonify(response), 200


@app.route("/log", methods=["GET"])
def log():
    limit = request.args.get("limit", 20, type=int)
    entries = get_log(limit)
    return jsonify({"entries": entries}), 200


@app.route("/status/<content_id>", methods=["GET"])
def status(content_id):
    entry = get_entry(content_id)
    if not entry:
        return jsonify({"error": "content_id not found"}), 404
    return jsonify(entry), 200


@app.route("/appeal", methods=["POST"])
def appeal():
    body = request.get_json(silent=True)
    if not body or "content_id" not in body or "creator_reasoning" not in body:
        return jsonify({"error": "Missing required fields: content_id, creator_reasoning"}), 400

    content_id = body["content_id"].strip()
    creator_reasoning = body["creator_reasoning"].strip()

    # Look up original decision
    entry = get_entry(content_id)
    if not entry:
        return jsonify({"error": "content_id not found"}), 404

    # Don't allow duplicate appeals
    if entry.get("appeal_id"):
        return jsonify({"error": "An appeal has already been filed for this content"}), 400

    appeal_id = str(uuid.uuid4())
    appealed_at = datetime.now(timezone.utc).isoformat()

    # Update audit log entry
    con = sqlite3.connect(DB_PATH)
    con.execute("""
        UPDATE audit_log
        SET status = 'under_review',
            appeal_id = ?,
            appeal_reason = ?,
            appealed_at = ?
        WHERE content_id = ?
    """, (appeal_id, creator_reasoning, appealed_at, content_id))
    con.commit()
    con.close()

    return jsonify({
        "appeal_id": appeal_id,
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal has been logged and is under review.",
    }), 200


# ---------------------------------------------------------------------------
# Init + run
# ---------------------------------------------------------------------------
init_db()

if __name__ == "__main__":
    app.run(debug=True, port=5000, host="0.0.0.0")